#workflow

name: Hello World 
on: 
  push: 
    paths:
      # - 'README.md'
      # - 'docs/**'
      # - '**.yaml'
    branches:
      # - 'main'
      # - '!dev/**'
  workflow_dispatch: 
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
            - run: echo This is Le Thi Thao, today is $TODAY

